### ISSUE TITLE
Help please embedding into CSS

### ISSUE THREAD

**Issue by agarciagonzalez** [google/domato#18]
I'm trying to make a grammar that embeds XML and XSL into CSS used in a private document editor, but I do not understand why I can not use:
```python
htmlgrammar.generate_symbol('style_value')
```
I created another section:

```python
<cssurl> = url(<xmlelement_xml>)
```
Error:
```python
...
...
  File "/Users/agarcia/domato/grammar.py", line 347, in _select_creator
    raise GrammarError('No creators for type ' + symbol)
grammar.GrammarError: No creators for type xmlelement_xml
```
Result should be:
```python
cssurl = URL(data:mimetype;<xml.....>)
```

**Comment by ifratric** [comment]
Hey there,
The error you are getting means that the grammar generator doesn't know how to generate the `<xmlelement_xml>` symbol. Somewhere in the current grammar (or the included grammars) you should have a rule that starts with 
`<xmlelement_xml> = `

**Comment by agarciagonzalez** [comment]
I have a xml.txt and xmlattrb.txt included in the bottom of xml.txt. But doesn't work. As example I used <cssurl> = url(<svgelement_svg>) and I got same error

**Comment by agarciagonzalez** [comment]
The error is always in this line
```<xml_style_value> = <import from=cssgrammar symbol=declaration5>```
Adding css.txt and cssproperties doesn't work, and I think there are some files including others that ends in a loop. Tried to fix it, but still getting this error because the import declaration.

**Comment by ifratric** [comment]
Hey, sorry for not replying sooner (I was away for a couple of days), did you resolve the issue? If not, I can take a look at your grammar files. You can either attach it here or mail it to ifratric@google.com
